# -*- coding: utf-8 -*-
from . import res_partner
from . import building
from . import level
from . import project
from . import reservation
from . import property
from . import generate_build
from . import add_pay_strategy
from . import payment_term
from . import request_reservation
from . import company_team
from . import inherit_account_move
from . import customer_payment
from . import inherit_account_payment
from . import inherit_account_journal
from . import approvals
from . import crm_lead
from . import reservation_log
from . import unit_pricelist
